### ISSUE TITLE
fatal error: 'Foundation/Foundation.h' file not found

### ISSUE THREAD

**Issue by igorclark** [fjolnir/Tranquil#13]
Hi! I'm on Mavericks, 10.9.5. I tried the binary install but it segfaulted; I found the thread in fjolnir/xnomad#58 and ran the pipe-curl-to-zsh script from the tranquil readme:

`curl -fsSkL https://raw.github.com/fjolnir/Tranquil/master/Tools/install.sh | /bin/zsh`

It got successfully all the way to the Tranquil build and then fell at a late hurdle. It got as far as installing all the following, with GMP being the last to succeed:

```
$ ls -l /usr/local/tranquil/
total 0
drwxr-xr-x   5 igor  admin  170  4 Nov 01:12 gmp
drwxr-xr-x   3 igor  admin  102  4 Nov 01:12 include
drwxr-xr-x   3 igor  admin  102  4 Nov 01:11 lemon
drwxr-xr-x   3 igor  admin  102  4 Nov 01:11 libffi
drwxr-xr-x   3 igor  admin  102  4 Nov 01:11 libffi-ios
drwxr-xr-x   7 igor  admin  238  4 Nov 01:11 llvm
drwxr-xr-x  14 igor  admin  476  4 Nov 01:12 src
```

Output of the failed build is below. I'm pretty sure my `brew` installation is OK (and `brew doctor` agrees). Wonder if you have any ideas how to fix this? Thanks very much!

```
Cloning Tranquil from GitHub...
Cloning into '/usr/local/tranquil/src'...
remote: Counting objects: 7648, done.
remote: Total 7648 (delta 0), reused 0 (delta 0), pack-reused 7648
Receiving objects: 100% (7648/7648), 4.30 MiB | 613.00 KiB/s, done.
Resolving deltas: 100% (3701/3701), done.
Checking connectivity... done.
Compiling...
mkdir -p /usr/local/tranquil/src/Build
ruby Source/Tranquil/gen_stubs_header.rb 32 > Build/TQStubs.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Build/TQStubs.h /usr/local/tranquil/include/Tranquil/Runtime/TQStubs.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/NSBlock+TQAdditions.h /usr/local/tranquil/include/Tranquil/Runtime/NSBlock+TQAdditions.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/NSCollections+Tranquil.h /usr/local/tranquil/include/Tranquil/Runtime/NSCollections+Tranquil.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/NSNumber+TQOperators.h /usr/local/tranquil/include/Tranquil/Runtime/NSNumber+TQOperators.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/NSObject+TQAdditions.h /usr/local/tranquil/include/Tranquil/Runtime/NSObject+TQAdditions.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/NSString+TQAdditions.h /usr/local/tranquil/include/Tranquil/Runtime/NSString+TQAdditions.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQBigNumber.h /usr/local/tranquil/include/Tranquil/Runtime/TQBigNumber.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQBlockClosure.h /usr/local/tranquil/include/Tranquil/Runtime/TQBlockClosure.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQBoxedObject.h /usr/local/tranquil/include/Tranquil/Runtime/TQBoxedObject.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQEnumerable.h /usr/local/tranquil/include/Tranquil/Runtime/TQEnumerable.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQFFIType.h /usr/local/tranquil/include/Tranquil/Runtime/TQFFIType.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQModule.h /usr/local/tranquil/include/Tranquil/Runtime/TQModule.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQNil.h /usr/local/tranquil/include/Tranquil/Runtime/TQNil.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQNothingness.h /usr/local/tranquil/include/Tranquil/Runtime/TQNothingness.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQNumber.h /usr/local/tranquil/include/Tranquil/Runtime/TQNumber.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQObject.h /usr/local/tranquil/include/Tranquil/Runtime/TQObject.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQPointer.h /usr/local/tranquil/include/Tranquil/Runtime/TQPointer.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQPromise.h /usr/local/tranquil/include/Tranquil/Runtime/TQPromise.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQProxy.h /usr/local/tranquil/include/Tranquil/Runtime/TQProxy.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQRange.h /usr/local/tranquil/include/Tranquil/Runtime/TQRange.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQRegularExpression.h /usr/local/tranquil/include/Tranquil/Runtime/TQRegularExpression.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQRootObject.h /usr/local/tranquil/include/Tranquil/Runtime/TQRootObject.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQRuntime.h /usr/local/tranquil/include/Tranquil/Runtime/TQRuntime.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQRuntimePrivate.h /usr/local/tranquil/include/Tranquil/Runtime/TQRuntimePrivate.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQValidObject.h /usr/local/tranquil/include/Tranquil/Runtime/TQValidObject.h
mkdir -p /usr/local/tranquil/include/Tranquil/Runtime
cp Source/Tranquil/Runtime/TQWeak.h /usr/local/tranquil/include/Tranquil/Runtime/TQWeak.h
mkdir -p /usr/local/tranquil/include/Tranquil/Shared
cp Source/Tranquil/Shared/TQBatching.h /usr/local/tranquil/include/Tranquil/Shared/TQBatching.h
mkdir -p /usr/local/tranquil/include/Tranquil/Shared
cp Source/Tranquil/Shared/TQDebug.h /usr/local/tranquil/include/Tranquil/Shared/TQDebug.h
mkdir -p /usr/local/tranquil/include/Tranquil/Shared
cp Source/Tranquil/Shared/khash.h /usr/local/tranquil/include/Tranquil/Shared/khash.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/CodeGen.h /usr/local/tranquil/include/Tranquil/CodeGen/CodeGen.h
mkdir -p /usr/local/tranquil/include/Tranquil/ObjcSupport
cp Source/Tranquil/CodeGen/ObjcSupport/TQHeaderParser.h /usr/local/tranquil/include/Tranquil/ObjcSupport/TQHeaderParser.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQArithmeticProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQArithmeticProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQBlockNamingProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQBlockNamingProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQDeallocInsertProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQDeallocInsertProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQInitInsertProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQInitInsertProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQMemoryManagementProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQMemoryManagementProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/Processors
cp Source/Tranquil/CodeGen/Processors/TQWeakProcessor.h /usr/local/tranquil/include/Tranquil/Processors/TQWeakProcessor.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNode+Private.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNode+Private.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNode.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNode.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeArgument.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeArgument.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeArgumentDef.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeArgumentDef.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeArray.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeArray.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeAsync.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeAsync.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeBlock.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeBlock.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeCall.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeCall.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeClass.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeClass.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeCollect.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeCollect.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeConditionalBlock.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeConditionalBlock.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeConstant.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeConstant.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeCustom.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeCustom.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeDictionary.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeDictionary.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeImport.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeImport.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeLock.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeLock.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeLoopBlock.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeLoopBlock.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeMemberAccess.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeMemberAccess.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeMessage.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeMessage.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeMethod.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeMethod.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeNil.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeNil.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeNothing.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeNothing.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeNumber.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeNumber.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeOperator.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeOperator.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeRegex.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeRegex.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeReturn.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeReturn.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeString.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeString.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeValid.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeValid.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeVariable.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeVariable.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQNodeWeak.h /usr/local/tranquil/include/Tranquil/CodeGen/TQNodeWeak.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQParse.h /usr/local/tranquil/include/Tranquil/CodeGen/TQParse.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQProgram+Internal.h /usr/local/tranquil/include/Tranquil/CodeGen/TQProgram+Internal.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQProgram+LLVMUtils.h /usr/local/tranquil/include/Tranquil/CodeGen/TQProgram+LLVMUtils.h
mkdir -p /usr/local/tranquil/include/Tranquil/CodeGen
cp Source/Tranquil/CodeGen/TQProgram.h /usr/local/tranquil/include/Tranquil/CodeGen/TQProgram.h
clang Source/Tranquil/Runtime/NSBlock+TQAdditions.m -arch x86_64 -DDEBUG -Wno-objc-root-class -Wno-objc-protocol-method-implementation -Wno-cast-of-sel-type -I`pwd`/Source -I/usr/local/tranquil/include -I`pwd`/Build -I/usr/local/tranquil/gmp/include -O0 -g -mmacosx-version-min=10.7 -I/usr/local/tranquil/libffi/include -isysroot `xcrun --sdk macosx --show-sdk-path` -F`xcrun --sdk macosx --show-sdk-path`/System/Library/Frameworks/ApplicationServices.framework/Frameworks -c -o build/NSBlock+TQAdditions.o.x64 -ObjC
clang: warning: no such sysroot directory: '-F/System/Library/Frameworks/ApplicationServices.framework/Frameworks'
In file included from Source/Tranquil/Runtime/NSBlock+TQAdditions.m:1:
In file included from Source/Tranquil/Runtime/NSBlock+TQAdditions.h:1:
/usr/local/tranquil/include/Tranquil/Runtime/TQStubs.h:5:9: fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^
1 error generated.
rake aborted!
Command failed with status (1): [clang Source/Tranquil/Runtime/NSBlock+TQAd...]
/usr/local/tranquil/src/Rakefile:121:in `compile'
/usr/local/tranquil/src/Rakefile:166:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => tranquil => libtranquil => build/NSBlock+TQAdditions.o
(See full trace by running task with --trace)
Error building tranquil!

real    42m13.053s
user    75m54.613s
sys     3m45.839s

```

**Comment by fjolnir** [comment]
Which version of xcode do you have installed?
Currently the header search paths are hardcoded in the compiler so it breaks every time they bump the SDK version. I need to change this to be dynamic/overridable

**Comment by igorclark** [comment]
Ah, looks like it was because I only had the CLI tools installed. Duh. So I installed the latest version of Xcode that I could for Mavericks - i.e. 6.2 / 6C131e - and then found other problems.

- The Ragel download URLs have changed. I've forked tranquil and updated the [install script](https://github.com/igorclark/Tranquil/blob/master/Tools/install.sh), and that version DLs Ragel OK.

- Ragel v6.7 just doesn't build on my Xcode, there are 4 instances of ```../aapl/bstcommon.h:460:17: error: use of undeclared identifier 'compare'```. So I changed the version to the latest from the Ragel site (6.9), which built fine.

- I hoped I had all the tools properly installed now, but Tranquil didn't want to build. I guessed this was now because of the SDK version issue you mentioned:

```
$ curl -fsSkL https://raw.githubusercontent.com/igorclark/Tranquil/master/Tools/install.sh | /bin/zsh 
I'm about to retrieve and compile Tranquil for you. This will take around 20 minutes,
depending on your connection & hardware of course.

Installing LLVM (This is the part that takes a while)...
You already have llvm installed.

Installing Ragel
You already have ragel installed.

Installing Lemon
You already have lemon installed.

Installing libffi
You already have libffi installed.

Installing GNU MP...
You already have GMP installed.

Updating Tranquil...
Already up-to-date.
Compiling...
mkdir -p /usr/local/tranquil/src/Build
clang Source/Tranquil/Runtime/TQBlockClosure.m -arch x86_64 -DDEBUG -Wno-objc-root-class -Wno-objc-protocol-method-implementation -Wno-cast-of-sel-type -I`pwd`/Source -I/usr/local/tranquil/include -I`pwd`/Build -I/usr/local/tranquil/gmp/include -O0 -g -mmacosx-version-min=10.7 -I/usr/local/tranquil/libffi/include -isysroot `xcrun --sdk macosx --show-sdk-path` -F`xcrun --sdk macosx --show-sdk-path`/System/Library/Frameworks/ApplicationServices.framework/Frameworks -c -o build/TQBlockClosure.o.x64 -ObjC
In file included from Source/Tranquil/Runtime/TQBlockClosure.m:1:
Source/Tranquil/Runtime/TQBlockClosure.h:3:9: fatal error: 'ffi.h' file not found
#import <ffi.h>
        ^
1 error generated.
rake aborted!
Command failed with status (1): [clang Source/Tranquil/Runtime/TQBlockClosu...]
/usr/local/tranquil/src/Rakefile:121:in `compile'
/usr/local/tranquil/src/Rakefile:166:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => tranquil => libtranquil => build/TQBlockClosure.o
(See full trace by running task with --trace)
Error building tranquil!
```
But I don't know enough about OSX dev to fix this. I looked in the Rakefile and search for 'sdk' and found lots of references to `xcrun`, so I tried running that to see what gives and I get this:

```
$ xcrun --sdk macosx --show-sdk-version
10.10
$ xcrun --sdk macosx --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
$ sw_vers -productVersion
10.9.5
```
Which, ok, what. According to https://github.com/Homebrew/homebrew/issues/33431#issuecomment-60314100 this is Apple's intended behaviour. Which seems pretty nuts to me, but whatever.

So I tried a quick hack of just adding `| sed 's/10\.10/10.9/g'` to the `xcrun` calls in `Rakefile` but, of course, no joy, just splurge of mismatched version errors because `clang` looks in a different place and blah blah blah. (And now I don't know how to properly get rid of Xcode and all the crap it leaves everywhere without hosing my CLI-only tools installation. Which is exactly why I never installed the full Xcode in the first place ;-))

Sorry, I suspect this is getting way out of the realms of anything to do with Tranquil! If you happen to know anything about how to fix this, or if this definitely just means that the Tranquil build won't work on Mavericks, then it'd be great if you could let me know - if not, of course, no sweat, and I'm sorry to have bugged you.

**Comment by igorclark** [comment]
OK forget all that, I have a much better question now ;-)

I realised that some of the libs & tools in `/usr/local/tranquil` were missing or not properly installed because of earlier failures, and when it was saying "You already have libffi installed" it was just checking the `/usr/local/tranquil/lemon` dir and assuming everything in there was cool.

So I started over, did a bit of digging around and [tweaked some minor details](https://github.com/igorclark/Tranquil/commit/015dd06fba0dc7bc77c5f0c3b1cad18dc5c55712) (which I think are mostly related to the different OSX/Xcode version), and now Tranquil builds on my 10.9.5 / Xcode 6.2 setup.

It builds (and runs!), but with a bunch of warnings (see [build output gist](https://gist.github.com/igorclark/8f53ff30020325c53023)) which I guess might be 10.9.5 issues, and I wonder whether they might be why I get this when I'm trying to run xnomad:

```
$ ./xnomad
2015-11-05 20:58:12.564 tranquil[8406:507] Source/Tranquil/Runtime/TQRuntime.m:93 (TQGetClass): Assertion failed: Class 'InstallEventHandler' does not exist
2015-11-05 20:58:12.565 tranquil[8406:507] *** Terminating app due to uncaught exception 'TQAssertFailed', reason: 'Class 'InstallEventHandler' does not exist'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff8fc9125c __exceptionPreprocess + 172
        1   libobjc.A.dylib                     0x00007fff8bb77e75 objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff8fc9110c +[NSException raise:format:] + 204
        3   tranquil                            0x00000001035b00d4 TQGetClass + 132
        4   ???                                 0x000000010859cdac 0x0 + 4435070380
        5   ???                                 0x000000010859d925 0x0 + 4435073317
        6   ???                                 0x00000001085922de 0x0 + 4435026654
        7   libtranquil_codegen.dylib           0x00000001036dec25 __32-[TQProgram _prepareRoot:error:]_block_invoke + 37
        8   tranquil                            0x000000010365dedf main + 1007
        9   libdyld.dylib                       0x00007fff9331a5fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

Thought of moving that over to an xnomad issue, but it seems like it's probably related to this. I'm guessing I'm maybe just not going to have much luck with this on Mavericks, does that sound like the case?

Really appreciate any pointers you might be able to give. I'd love to get xnomad working, it looks amazing, but if it's just a no-go on Mavericks then I should stop taking up your (and my) time :-)

**Comment by igorclark** [comment]
Hello again, I tried to run the binary version on Yosemite on a Macbook but that segfaulted too. So I just tried to build Tranquil on it (`10.10.5` with Xcode `Version 7.1 (7B91b)`), and now I guess I'm getting to the real issue that you mentioned with the SDK versions, as I got this:

```
/usr/local/tranquil/include/Tranquil/Runtime/TQRuntime.h:3:9: fatal error: 'Foundation/Foundation.h' file not found
```
presumably because of this:

```
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk'
```
Which is dead right, it doesn't exist. In fact, even though I just installed Xcode on Yosemite from the App Store with all the default settings, the only SDK directory in there is `MacOSX10.11.sdk`. (Apple, wtf? Weird setup.)

So I went through and changed all the references to `10.9` in the Tranquil tree to `10.11`:

```
Source/Tranquil/CodeGen/ObjcSupport/TQHeaderParser.mm
Source/Tranquil/CodeGen/TQProgram.mm
Tools/tqc.tq
```
Build output [here](https://gist.github.com/igorclark/2a7858a771e3d3cea62c), upshot being a bunch of these:

```
error: expected a type
- (id)copyWithZone:(nullable NSZone *)zone;
                    ^
```
and these:

```
error: expected ';' after @class
@class NSArray<ObjectType>;
              ^
```
which happen when `rake` tries to run

```
/usr/local/tranquil/bin/tranquil Tools/tqc.tq Tools/tqc.tq -o /usr/local/tranquil/bin/tqc
```
with what looks like the root problem starting at

```
In file included from /usr/local/tranquil/share/tqmain.m:2:
In file included from /usr/local/tranquil/include/Tranquil/Runtime/TQRuntime.h:3:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: expected a type
- (id)copyWithZone:(nullable NSZone *)zone;
                    ^
[…]
In file included from /usr/local/tranquil/include/Tranquil/Runtime/TQRuntime.h:3:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
@class NSArray<ObjectType>;
              ^
```

Which I'm _guessing_ is something to do with new Obj-C features (generics?) not being understood by Tranquil? Or maybe something like that.

So for me, current status seems to be:

- binary install segfaults on 10.9.5 and 10.10.5
- builds on 10.9.5 but crashes on xnomad
- won't build on 10.10.5

All of which seems like it might be because I'm just trying to pick up a project that's had a bunch of stuff pulled out from under its feet by Apple. Boo.

Anyway, thanks for your time. Would still love to get this going, but at this point I think I'm reluctantly going to have to give up unless there's some obvious reason, or unless I'm doing something dumb :-(

**Comment by fjolnir** [comment]
Sorry to take so long.

I took a look at building with the El Capitan SDK. But the problem is that it uses the new swift compatibility syntax additions which the version of llvm tranquil is using does not support. And between that version of llvm and the current one, the API has changed immensely. So migrating to it is not a simple matter.

So for now I'd consider tranquil/xnomad abandoned. I'll still keep playing with it and might even get it running again. But I don't have any timelines or guarantees ^^;

**Comment by igorclark** [comment]
Hey, no worries, thanks for getting back to me!

Right, glad to hear I was vaguely on the right lines, sorry to hear it means (what sounds like) a big pile of work to port to the new API. Totally understand if you don't have time. Seems a real shame they just broke it, because you obviously put a lot of effort into the projects, and tranquil in particular seems pretty amazing. Well, so it goes.

Will keep a "watch" on the project but won't hold my breath.

Thanks anyway, Fjölnir :+1:
